name: pull request to main branch and check if the build is successful
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install and Build NPM 🔧
        run: |
          cd component
          npm install
          npm run build:module
      - name: Install and Build Wesbite 🔧
        run: |
          cd website
          npm install
          npm run build
